import os
from pathlib import Path
import urllib.parse
import requests

# PocketBase API Environment Constants
PB_BASE_URL = os.environ.get("PB_BASE_URL", "https://unf.wavelynxtech.com/api")
PB_COLLECTION_ID = os.environ.get("PB_COLLECTION_ID", "kceqp1an569q6sp")
PB_ADMIN_TOKEN = os.environ.get(
    "PB_ADMIN_TOKEN",
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODc1OTE0NjIsImlkIjoic2VvNHN2bHc1Njdhcmk0IiwidHlwZSI6ImFkbWluIn0.UE38lHM1PBzTUi7gz9dbgKEZ7N0QeDw35lrn9xnD1G0",
)


class PocketBaseClient:
    """Client for interacting with PocketBase REST API endpoints.

    Used to query token cache and upload binary assets.

    Attributes:
        base_url (str): The base REST URL of the PocketBase instance.
        collection_id (str): The PocketBase target collection identifier.
        admin_token (str): Admin bearer token for REST authorization.
    """

    def __init__(
        self,
        base_url: str = PB_BASE_URL,
        collection_id: str = PB_COLLECTION_ID,
        admin_token: str = PB_ADMIN_TOKEN,
    ):
        """Initializes PocketBaseClient with connection settings.

        Args:
            base_url (str, optional): PocketBase API endpoint. Defaults to PB_BASE_URL.
            collection_id (str, optional): Target collection ID. Defaults to PB_COLLECTION_ID.
            admin_token (str, optional): Admin bearer token. Defaults to PB_ADMIN_TOKEN.
        """
        self.base_url = base_url.rstrip("/")
        self.collection_id = collection_id
        self.admin_token = admin_token

    def _get_headers(self) -> dict:
        """Constructs headers containing authorization token.

        Returns:
            dict: Header mapping with Bearer authorization token.
        """
        return {"Authorization": f"Bearer {self.admin_token}"}

    def check_active_token(self, token_name: str) -> str | None:
        """Queries PocketBase to check if an active token record exists.

        Args:
            token_name (str): Name of the configuration token to check.

        Returns:
            str | None: Active token value or ID if found in cache, else None.
        """
        filter_query = f'name = "{token_name}" && status = "ACTIVE"'
        encoded_filter = urllib.parse.quote(filter_query)
        url = f"{self.base_url}/collections/{self.collection_id}/records?filter={encoded_filter}"

        try:
            response = requests.get(url, headers=self._get_headers(), timeout=10)
            if response.status_code == 200:
                items = response.json().get("items", [])
                if items:
                    token_val = items[0].get("token") or items[0].get("id")
                    print(
                        f"[PocketBase Client] Cache HIT for '{token_name}' ->"
                        f" {token_val}"
                    )
                    return token_val
        except Exception as e:
            print(f"[PocketBase Warning] Cache query failed: {e}")

        print(f"[PocketBase Client] Cache MISS for '{token_name}'")
        return None

    def create_token_record(self, token_name: str, local_bin_path: Path) -> str:
        """Uploads a compiled binary file asset (.bin/.dck) and registers a new ACTIVE token record.

        Args:
            token_name (str): The configuration token name.
            local_bin_path (Path): Path to the compiled binary asset on disk.

        Returns:
            str: Token value or record ID generated by PocketBase.

        Raises:
            Exception: If registration fails or server returns error status code.
        """
        url = f"{self.base_url}/collections/{self.collection_id}/records"

        with open(local_bin_path, "rb") as f:
            multipart_payload = {
                "name": (None, token_name),
                "status": (None, "ACTIVE"),
                "card": (local_bin_path.name, f, "application/octet-stream"),
            }
            response = requests.post(
                url, headers=self._get_headers(), files=multipart_payload, timeout=30
            )

        if response.status_code in [200, 201]:
            data = response.json()
            token_val = data.get("token") or data.get("id")
            print(
                f"[PocketBase Client] Created token record for '{token_name}'"
                f" -> {token_val}"
            )
            return token_val
        else:
            raise Exception(
                f"PocketBase Registration Failed ({response.status_code}):"
                f" {response.text}"
            )